name: timeware_test
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.7.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  go_router: ^14.1.2
  dio: ^5.4.3+1
  json_annotation: ^4.8.0
  flutter_widget_from_html: ^0.15.0

  cupertino_icons: ^1.0.6
  flutter_secure_storage: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.1
  build_runner: ^2.4.10

  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/images/
  uses-material-design: true
